server.port=${8080}
# 替换为自己应用的appKey
dingtalk.app_key=${ding1ot6ueurjkjcnoxw}
# 替换为自己应用的appSecret
dingtalk.app_secret=${FeTCcG-W9ialuHoXyOawcmj64jLlg14KEIXwssPpg9kOMj2hqnEQHuxPgkrdAuA7}

dingtalk.agent_id=${3390659524}

#corpId
dingtalk.corp_id=${ding03a54b373077705524f2f5cc6abecb85}

